name: Get Last Release Tag

on:
  pull_request:
    branches:
      - main

jobs:
  get_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Increment version from repository's tags
        id: tages_versioning
        uses: georgeneto/tags-versioning@v1
        with:
          repo-token: ${{secrets.PAT}}


      - name: Use the release tag
        run: |
          echo "The last release tag is ${{ steps.version.outputs.last }}"
