name: Get Last Release Tag changed

on:
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Check for changes in 'apps/mobile/**'
        id: check_changes
        run: echo ::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

  get_tag:
    runs-on: ubuntu-latest
    needs: check_changes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Increment version from repository's tags
        id: tages_versioning
        uses: georgeneto/tags-versioning@v1
        with:
          repo-token: ${{secrets.PAT}}


      - name: Use the release tag
        env:
          LAST_RELEASE_TAG: ${{ steps.tages_versioning.outputs.last || '0.0.0' }}
        run: |
          echo "The last release tag is $LAST_RELEASE_TAG"
          echo "The next release tag is ${{ steps.tages_versioning.outputs.next}}"
          
      - name: Determine Tag Name
        id: determine_tag
        run: |
          if [[ -n "${{ steps.tages_versioning.outputs.last}}" ]]; then
            echo "::set-output name=tag_name::${{ steps.tages_versioning.outputs.next }}"
          else
            echo "::set-output name=tag_name::V1.0.0"
          fi
      - name: see tag name
        run: echo ${{ steps.determine_tag.outputs.tag_name }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ steps.determine_tag.outputs.tag_name }}
          name: Release ${{ steps.increment-release-tag.outputs.new_tag }}
          draft: false
          prerelease: false
          body: |
            Release notes for ${{ steps.increment-release-tag.outputs.new_tag }}

      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=release_id::${{ github.event.outputs.create_release.id }}"

      - name: Use Release ID
        run: |
          echo "Created release with ID ${{ steps.get_release_id.outputs.release_id }}"
