name: Get Last Release Tag

on:
  pull_request:
    branches:
      - main

jobs:
  get_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Increment version from repository's tags
        id: tages_versioning
        uses: georgeneto/tags-versioning@v1
        with:
          repo-token: ${{secrets.PAT}}


      - name: Use the release tag
        env:
          LAST_RELEASE_TAG: ${{ steps.tages_versioning.outputs.next || '0.0.0' }}
        run: |
          echo "The last release tag is $LAST_RELEASE_TAG"
          echo "The last release tag is ${{ steps.tages_versioning.outputs}}"
          
      - name: Determine Tag Name
        id: determine_tag
        run: |
          if [[ "${{ steps.tages_versioning.outputs.last }}" == "true" ]]; then
            echo "::set-output name=tag_name::1.0.0"
          else
            echo "::set-output name=tag_name::${{ steps.tages_versioning.outputs.next }}"
          fi
      
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.determine_tag.outputs.tag_name }}
          release_name: Release ${{ steps.determine_tag.outputs.tag_name }}
          draft: false
          prerelease: false
          body: |
            Release notes for ${{ steps.determine_tag.outputs.tag_name }}
