name: Get Last Release Tag

on:
  pull_request:
    branches:
      - main

jobs:
  get_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment version from repository's tags
        id: tages_versioning
        uses: georgeneto/tags-versioning
        with:
          repo-token: ${{secrets.PAT}}


      - name: Use the release tag
        run: |
          echo "The last release tag is ${{ steps.version.outputs.last }}"
